# -*- coding: utf-8 -*-
"""desafio_final_real.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B33DiOdAn4dRpCGzSSllLhHvMWUoZpn_

# Análise exploratória dos dados
O dataset que iremos trabalhar possui os seguintes (principais) atributos:

- **rec_id** :  índice do registro de locação;
- **datetime** : data;
- **season** :  estação do ano (1: inverno, 2: primavera, 3: verão, 4: outono). Relativo ao 
hemisfério norte;
- **year**: ano (0: 2011, 1:2012);
- **month** : mês (1 a 12);
- **hour**  : hora do dia (0 a 23);
- **is_holiday** : booleano indicando feriado;
- **weekday** : dia da semana (0: domingo, 1: segunda-feira, …, 6: sábado);
- **is_workingday** : booleano indicando dia útil;
- **weather_condition** : (1: limpo, 2: nublado, 3: chuva leve, 4: chuva forte);
- **temp** : : Temperatura escalada entre 0 e 1. Valor original em graus Celsius: -8 a 39
- **atemp** :  Sensação térmica escalada entre 0 e 1. Valor original em graus Celsius: -16 a 50;
- **humidity** : Humidade relativa (0 a 1);
- **windspeed** : : Velocidade do vento escalada entre 0 e 1 (máximo original: 67);
- **casual**: número de locações para usuários casuais;
- **registered**: número de locações para usuários registrados;
- **total_count**:contador total de aluguéis (casual+registered).
"""

"""
Na primeira execução deste notebook,
atualize a versão dos seguintes pacontes, é só descomentar as seguintes linhas
e executar a célula.

Após a atualização, lembre-se de reiniciar o Kernel do notebook.
"""
#!pip install --upgrade numpy
#!pip install --upgrade pandas
#!pip install --upgrade matplotlib

# importando as bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""# Limpeza e leitura de dados

Realizando a importação do dataset <https://pycourse.s3.amazonaws.com/bike-sharing.csv> para 
análise utilizando o pandas
"""

df = pd.read_csv('https://pycourse.s3.amazonaws.com/bike-sharing.csv')
df.head()

"""
DICA: pandas profile https://github.com/pandas-profiling/pandas-profiling
Para instalar, descomente e execute as seguintes linhas.
"""
#!pip install pandas-profiling
#!pip install --upgrade pandas-profiling

# descritivo dos dados
from pandas_profiling import ProfileReport

profile = ProfileReport(df, title="Uso de bicicleta")

profile

df.info()

"""Segundo o pandas profile e pela função info no dataframe é possivel observar que todas as colunas possuem seus dados de forma igual. Contudo, caso não estivem colunas que possuissem algum dado faltante poderia ser utilizada o seguite codigo:

`df.drop ([objeto que deseja trabalhar],        axis='columns',inplace=True)`


e a segunda estrategia para limpeza é realizar a remoção de colunas com pouca varriabilidade ou irrelevante para a anális, que pode ser utilizada a mesma função, que no caso deste dataframe será as colunas de índice do registro de locação, e as datas data, contudo será somente para este caso, talvez para outro tipos de análise tais counas podem ser relevantes.
"""

df.drop(['datetime',],
         axis='columns',
         inplace=True)

df.info()

# definindo a xolkuno rec_id como indice
df.set_index('rec_id',inplace=True)
df.head()

# medias da coluna windsoeed, temp
df[['windspeed', 'temp']].mean().plot.bar()

# contando os registros no ano
df["year"].value_counts().plot.bar()

# Quantas locações foram registradas para 2011 e 2012
fig, axs = plt.subplots()
axs.bar('year', 'total_count').sum()

#Qual estação do ano possui a maior média de locações
df.groupby(by = ['season'])['total_count'].mean().sort_values(ascending = False)

